<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BLR1-LHP-N71882" ignored="0" name="CreateNewAccount" tests="1" failures="1" timestamp="2021-02-04T12:39:57 IST" time="29.075" errors="0">
  <testcase name="createNewAccountTest" time="22.181" classname="com.demo.tests.CreateNewAccountTest">
    <failure type="java.lang.AssertionError" message="The error is not matching expected [Too many users have this phone number listed as pending.] but found [Too many users have this phone number listed as pending.3344]">
      <![CDATA[java.lang.AssertionError: The error is not matching expected [Too many users have this phone number listed as pending.] but found [Too many users have this phone number listed as pending.3344]
at com.demo.tests.CreateNewAccountTest.createNewAccountTest(CreateNewAccountTest.java:28)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- createNewAccountTest -->
</testsuite> <!-- CreateNewAccount -->
